In [1]:
import numpy as np
import pandas as pd

In [2]:
r = np.array([[3.96842486, 5.81538461, 3.32983614],
     [6.73876709, 6.80626654, 5.29123315],
     [7.73792884, 7.49007395, 5.29123315]
    ])
r

array([[3.96842486, 5.81538461, 3.32983614],
       [6.73876709, 6.80626654, 5.29123315],
       [7.73792884, 7.49007395, 5.29123315]])

In [3]:
r_inverse = 1/r
pd.DataFrame(r_inverse)

0         1         2
0  0.251989  0.171958  0.300315
1  0.148395  0.146923  0.188992
2  0.129234  0.133510  0.188992

In [4]:
1/3.96842486

0.25198914815789153

In [5]:
A_matrix = np.einsum("ij, ik -> jk", r_inverse, r_inverse)
pd.DataFrame(A_matrix)

0         1         2
0  0.102221  0.082388  0.128146
1  0.082388  0.068981  0.104641
2  0.128146  0.104641  0.161625

In [40]:
B_vector = np.zeros(ndim)
B_vector

array([0., 0., 0., 0., 0.])

In [6]:
0.25198914815789153 * 0.25198914815789153

0.06349853078933981

In [7]:
A_matrix[:3, :3]

array([[0.10222095, 0.08238816, 0.1281457 ],
       [0.08238816, 0.06898086, 0.10464112],
       [0.1281457 , 0.10464112, 0.16162499]])

In [8]:
A_matrix[:3, :3] += 1.0
pd.DataFrame(A_matrix)

0         1         2
0  1.102221  1.082388  1.128146
1  1.082388  1.068981  1.104641
2  1.128146  1.104641  1.161625

In [9]:
# replaces a column
A_matrix[:3, 2] = 1
pd.DataFrame(A_matrix)

0         1    2
0  1.102221  1.082388  1.0
1  1.082388  1.068981  1.0
2  1.128146  1.104641  1.0

In [17]:
n_constraints = 1
ndim = 3 + n_constraints + 1

In [30]:
A_matrix = np.zeros((ndim, ndim))
pd.DataFrame(A_matrix)

0    1    2    3    4
0  0.0  0.0  0.0  0.0  0.0
1  0.0  0.0  0.0  0.0  0.0
2  0.0  0.0  0.0  0.0  0.0
3  0.0  0.0  0.0  0.0  0.0
4  0.0  0.0  0.0  0.0  0.0

In [31]:
# substitute values
A_matrix[:3, :3] += np.einsum("ij, ik -> jk", r_inverse, r_inverse)
A_matrix

array([[0.10222095, 0.08238816, 0.1281457 , 0.        , 0.        ],
       [0.08238816, 0.06898086, 0.10464112, 0.        , 0.        ],
       [0.1281457 , 0.10464112, 0.16162499, 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ]])

In [43]:
# Substitute 1 in column 3
# [row, column]
A_matrix[:3, 3] = 1
B_vector[3] = 1.0
B_vector

display(pd.DataFrame(A_matrix))
display(pd.DataFrame(B_vector))

0         1         2    3    4
0  0.102221  0.082388  0.128146  1.0  0.0
1  0.082388  0.068981  0.104641  1.0  0.0
2  0.128146  0.104641  0.161625  1.0  0.0
3  1.000000  1.000000  1.000000  0.0  0.0
4  0.000000  0.000000  0.000000  0.0  0.0

0
0  0.0
1  0.0
2  0.0
3  1.0
4  0.0

In [34]:
# substitute value in next non-element row
A_matrix[3, :3] = 1
pd.DataFrame(A_matrix)

0         1         2    3    4
0  0.102221  0.082388  0.128146  1.0  0.0
1  0.082388  0.068981  0.104641  1.0  0.0
2  0.128146  0.104641  0.161625  1.0  0.0
3  1.000000  1.000000  1.000000  0.0  0.0
4  0.000000  0.000000  0.000000  0.0  0.0

In [38]:
-0.6002604772446537/0.53

-1.1325669381974597

In [42]:
B_vector[3] = 1.0
B_vector

array([0., 0., 0., 1., 0.])